version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ec2-user

  
