version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
ApplicationStop:
    - location: stop.sh
      timeout: 60
      runas: ec2-user
ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: install.sh
      timeout: 60
      runas: ec2-user

  
