trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  ECR_URI: '474668397798.dkr.ecr.us-east-1.amazonaws.com/spring-boot-app'
  CLUSTER_NAME: 'eks-dev-cluster'
  TF_IN_AUTOMATION: 'true'

stages:
  - stage: TerraformEKS
    displayName: 'Terraform EKS Apply'
    jobs:
      - job: Terraform
        displayName: 'Provision EKS via Terraform'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.6.6'

          # ✅ AWS credentials are configured correctly here
          - task: aws-credentials-setup@1
            displayName: 'Configure AWS Credentials'
            inputs:
              awsCredentials: 'aws-devops-admin'

          - checkout: self

          - script: terraform init
            displayName: 'Terraform Init'
            workingDirectory: $(Build.SourcesDirectory)

          - script: terraform validate
            displayName: 'Terraform Validate'
            workingDirectory: $(Build.SourcesDirectory)

          - script: terraform plan -out=tfplan
            displayName: 'Terraform Plan'
            workingDirectory: $(Build.SourcesDirectory)

          - script: terraform apply -auto-approve tfplan
            displayName: 'Terraform Apply'
            workingDirectory: $(Build.SourcesDirectory)

  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image'
    dependsOn: TerraformEKS
    jobs:
      - job: Build
        displayName: 'Docker Build & Push'
        steps:
          - checkout: self

          - task: AWSCLI@1
            name: awsCreds
            displayName: 'Get AWS Credentials'
            inputs:
              awsCredentials: 'aws-devops-admin'
              awsRegion: '$(AWS_REGION)'
              awsCommand: 'sts'
              awsSubCommand: 'get-caller-identity'
              outputVariables: 'awsAccessKeyId,awsSecretAccessKey,awsSessionToken'

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests'
            displayName: 'Build Spring Boot App'

          - script: docker build -t $(ECR_URI):latest .
            displayName: 'Build Docker Image'

          - script: |
              aws ecr get-login-password --region $(AWS_REGION) \
              | docker login --username AWS --password-stdin $(ECR_URI)
            displayName: 'Docker Login to ECR'
            env:
              AWS_ACCESS_KEY_ID: $(awsCreds_awsAccessKeyId)
              AWS_SECRET_ACCESS_KEY: $(awsCreds_awsSecretAccessKey)
              AWS_SESSION_TOKEN: $(awsCreds_awsSessionToken)

          - script: docker push $(ECR_URI):latest
            displayName: 'Push Image to ECR'

  - stage: DeployToEKS
    displayName: 'Deploy to EKS'
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        displayName: 'Kubernetes Deploy'
        steps:
          - checkout: self

          - task: AWSCLI@1
            name: awsCreds
            displayName: 'Get AWS Credentials'
            inputs:
              awsCredentials: 'aws-devops-admin'
              awsRegion: '$(AWS_REGION)'
              awsCommand: 'sts'
              awsSubCommand: 'get-caller-identity'
              outputVariables: 'awsAccessKeyId,awsSecretAccessKey,awsSessionToken'

          - script: |
              aws eks update-kubeconfig --name $(CLUSTER_NAME) --region $(AWS_REGION)
            displayName: 'Configure kubectl'
            env:
              AWS_ACCESS_KEY_ID: $(awsCreds_awsAccessKeyId)
              AWS_SECRET_ACCESS_KEY: $(awsCreds_awsSecretAccessKey)
              AWS_SESSION_TOKEN: $(awsCreds_awsSessionToken)

          - script: |
              kubectl apply -f deployment/deployment.yaml
              kubectl apply -f deployment/service.yaml
            displayName: 'Deploy to EKS'
