- stage: TerraformEKS
  displayName: 'Provision EKS via Terraform'
  jobs:
    - job: Terraform
      displayName: 'Run Terraform'
      steps:
        - checkout: self

        - task: AWSCLI@1
          name: awsCreds
          displayName: 'Get AWS Credentials'
          inputs:
            awsCredentials: 'aws-devops-admin'
            awsRegion: '$(AWS_REGION)'
            awsCommand: 'sts'
            awsSubCommand: 'get-caller-identity'
            outputVariables: 'awsAccessKeyId,awsSecretAccessKey,awsSessionToken'

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.6.6'

        - script: |
            export AWS_ACCESS_KEY_ID=$(awsCreds_awsAccessKeyId)
            export AWS_SECRET_ACCESS_KEY=$(awsCreds_awsSecretAccessKey)
            export AWS_SESSION_TOKEN=$(awsCreds_awsSessionToken)

            terraform init
          displayName: 'Terraform Init'

        - script: |
            export AWS_ACCESS_KEY_ID=$(awsCreds_awsAccessKeyId)
            export AWS_SECRET_ACCESS_KEY=$(awsCreds_awsSecretAccessKey)
            export AWS_SESSION_TOKEN=$(awsCreds_awsSessionToken)

            terraform plan -out=tfplan
          displayName: 'Terraform Plan'

        - script: |
            export AWS_ACCESS_KEY_ID=$(awsCreds_awsAccessKeyId)
            export AWS_SECRET_ACCESS_KEY=$(awsCreds_awsSecretAccessKey)
            export AWS_SESSION_TOKEN=$(awsCreds_awsSessionToken)

            terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'
