version: 0.2

phases:
  install:
    commands:
      - echo "Installing Java 17 and Maven on Amazon Linux 2023..."
      - sudo dnf install -y java-17-amazon-corretto
      - sudo dnf install -y maven
      - java -version
      - mvn -version

  build:
    commands:
      - echo "Running Maven build..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Build completed successfully on $(date)"

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes
